---
- hosts: local
  tasks:
  - name: Create logical volumes
    lvol: vg=vg_gluster lv={{ item.name }} size={{ item.size }}
    with_items: "{{ local_pvs }}"

  - name: Create backing filesystems
    filesystem: fstype=xfs dev=/dev/vg_gluster/{{ item.name }} opts='-i size=512'
    with_items: "{{ local_pvs }}"

  - name: Mount backing filesystems
    mount: name=/data/{{ item.name }} src=/dev/vg_gluster/{{ item.name }} fstype=xfs state=mounted
    with_items: "{{ local_pvs }}"

  - name: Set backing filesystem permissions
    file: path=/data/{{ item.name }} state=directory owner=root group=root mode=0775 setype=svirt_sandbox_file_t
    with_items: "{{ local_pvs }}"
